version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80