version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: books
      DB_USERNAME: carter
      DB_PASSWORD: password
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db



  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books
      MYSQL_USER: carter
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db-data:
